### ISSUE TITLE
Server.sendChat ._.

### ISSUE THREAD

**Issue by ghost** [MCMrARM/toolbox-issue-tracker#59]
When i run Server.sendChat("/help");
It SAYS the command NOT running it ._. a toolbox bug?

**Comment by Johnmacrocraft** [comment]
@Smasher535 Did you tried using ./ instead of /? Because now there's also command system in 0.16.0, they were causing some problems with server commands. So as alternative way, server core developer started to use ./. If this isn't problem, please tell me what server did you had issue, so I can look for it and say why this happens.

**Comment by Johnmacrocraft** [comment]
@Smasher535 Did you try using ./ instead of /? Because now there's also command system in 0.16.0, they were causing some problems with server commands. So as alternative way, server core developer started to use ./. If this isn't problem, please tell me what server did you had issue, so I can look for it and say why this happens.

**Comment by ghost** [comment]
This got fixed in 1.0.0.16
